### ISSUE TITLE
Where do efi_get_variable() function come from?

### ISSUE THREAD

**Issue by tyan-boot** [rhinstaller/efibootmgr#26]
I wonder where do these function come from(which header file).

**Comment by CaptainFlint** [comment]
It's from efivar.h:
https://github.com/rhinstaller/efivar/blob/master/src/efivar.h

**Comment by tyan-boot** [comment]
Is this func

**Comment by tyan-boot** [comment]
Is this function a system API?

**Comment by CaptainFlint** [comment]
I gave link directly to that project's repo. It's efivar library, efibootmgr requires it to be installed.

**Comment by tyan-boot** [comment]
thank you.

2015年3月23日 下午7:09于 Konstantin Vlasov <notifications@github.com>写道：
I gave link directly to that project's repo. It's efivar library, efibootmgr requires it to be installed.

---
