### ISSUE TITLE
EDD10_HARDWARE_VENDOR_PATH_GUID redefined

### ISSUE THREAD

**Issue by cbrune** [rhinstaller/efibootmgr#29]
with the latest efivar and efibootmgr it looks like `EDD10_HARDWARE_VENDOR_PATH_GUID` is defined in *both* `/usr/include/efivar/efivar-dp.h` and efibootmgr's `src/include/efi.h`.

Removing it from src/include/efi.h allowed the build to proceed

**Comment by vathpela** [comment]
Yeah, this is yet another thing fixed on the dp branch - I'll try to get a release out very soon now :)
