### ISSUE TITLE
Segfault with -v when encountering empty option

### ISSUE THREAD

**Issue by mbfraga** [rhinstaller/efibootmgr#33]
When I was running efibootmgr, I was getting several empty options (B and C below). When I would run efibootmgr -v, I would get a segfault when reaching Boot00B. 
Boot0000 Setup
...
Boot000A* Fedora
Boot000B
Boot000C

I was using it under the archlinux installer 2015.06.01, using efibootmgr 0.11.0.

I had to manually delete the empty options in order to avoid the segfault.

**Comment by vathpela** [comment]
Does this still happen with efibootmgr 0.12 for you?  If I do this, it seems to work:
[root@fenchurch ~]# efibootmgr -c -L ''
BootCurrent: 0018
Timeout: 1 seconds
BootOrder: 0019,0000,0001,0002,0003,0018,0007,0008,0009,000B,000A,000C,000D,000E,000F,0010,0011,0012
Boot0000  Setup
...
Boot0018* Fedora
Boot0019* 
[root@fenchurch ~]# efibootmgr -v 0019
BootCurrent: 0018
Timeout: 1 seconds
BootOrder: 0019,0000,0001,0002,0003,0018,0007,0008,0009,000B,000A,000C,000D,000E,000F,0010,0011,0012
Boot0000  Setup	FvFile(721c8b66-426c-4e86-8e99-3457c46ab0b9)
...
Boot0018* Fedora	HD(1,GPT,575a990f-d7c9-4f1f-8b22-9d75e080c633,0x800,0x64000)/File(\EFI\fedora\shim.efi)
Boot0019* 	HD(1,GPT,575a990f-d7c9-4f1f-8b22-9d75e080c633,0x800,0x64000)/File(\EFI\redhat\grub.efi)
[root@fenchurch ~]# efibootmgr -b 0019 -B
BootCurrent: 0018
Timeout: 1 seconds
BootOrder: 0000,0001,0002,0003,0018,0007,0008,0009,000B,000A,000C,000D,000E,000F,0010,0011,0012
Boot0000  Setup
...
Boot0018* Fedora
[root@fenchurch ~]#

**Comment by vathpela** [comment]
(I'm going to close this on the assumption that it has been solved; if that's wrong, please respond with there results asked for in https://github.com/rhinstaller/efibootmgr/issues/33#issuecomment-114871823 and re-open the issue.)
