### ISSUE TITLE
Cannot create boot entry with extra arguments

### ISSUE THREAD

**Issue by balticer** [rhinstaller/efibootmgr#36]
Hello,

tryed

efibootmgr -d /dev/sda -p 1 -c -L "Arch Linux" -l /vmlinuz-linux -u "root=/dev/sda2 rw initrd=/initramfs-linux.img"

fails with

efibootmgr: Could not set variable: Invalid argument
efibootmgr: Could not prepare boot variable: Invalid argument

. Same arguments working with 0.11.0.

regards

**Comment by jared-dominguez** [comment]
It would probably help to state what versions of efibootmgr and libefivar you're using.

**Comment by balticer** [comment]
Hi,

sure, i'm sorry: efibootmgr 0.12 and efivar 0.20

regards

**Comment by benjarobin** [comment]
The bug is around the first call to efi_loadopt_create which doesn't allow dp = NULL

**Comment by benjarobin** [comment]
The bug was already referenced here : https://github.com/rhinstaller/efivar/issues/22

**Comment by vathpela** [comment]
This is fixed in efivar-0.21 with https://github.com/rhinstaller/efivar/commit/d07807c80cffa32460c10ddb0f76ac49d9c00387 .  Thanks for the report!
