### ISSUE TITLE
-u seems broken with multiple arguments

### ISSUE THREAD

**Issue by simonthum** [rhinstaller/efibootmgr#45]
When creating (modification not tested) a boot entry with -u and multiple arguments, the boot args get garbled. It seems to work well with one argument, or in ascii mode.

```
> locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

It looks like argument string length is misinterpreted in unicode  so offsets don't work for conatenation. I do

```
efibootmgr -d /dev/sda -c -L "label" -l \\EFI\\Lnx\\Boot\\kernel4.2.bzimage.efi -u root=/dev/sda8 atkbd.reset=1 i8042.nomux=1 i8042.reset=1
```

and get (efiboomgr -v excerpt)

```
image.efi)r.o.o.t.=./.d...a.t.k.b.d...r..i.8.0.4.2...n..i.8.0.4.2...r.e.s.e.t.=.1.
```

Obviously, that doesn't boot well. Without -u, things are fine.

Efribootmgr 0.12 on vanilla kernel 4.2

**Comment by cmason37** [comment]
-u works just fine if you put the options in quotation marks.

**Comment by simonthum** [comment]
Actually I discovered later that my locales got messed up by my X session, so if the issue is not reproducible please just close it.

@cmason37  I don't remember if I tried quotation marks - which ones do you mean? single/double?

**Comment by vathpela** [comment]
I don't understand what the issue is here /at all/.  Your sample output looks correct to me.

**Comment by cmason37** [comment]
@vathpela  Parts of the output are truncated.
